version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    expose:
      - "5000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
